#!/usr/bin/env python3
'''
Build the HTML documentation using `SphinxDoc <http://www.sphinx-doc.org>`_.
'''
import shutil
import sphinx

shutil.rmtree('doc/.doctrees/', ignore_errors=True)
shutil.rmtree('doc/_build/', ignore_errors=True)
sphinx.build_main(['', 'doc', 'doc/_build/'])
